version: '3'
services:
  app:
    build: ./
    container_name: open-flights-app
    ports:
      - 3000:3000
    env_file:
      - ./.envs/.production/postgres.env
      - ./.envs/.production/app.env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: open-flights-db
    env_file:
      - ./.envs/.production/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local